
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xyxizdssuxacqexyomqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5eGl6ZHNzdXhhY3FleHlvbXFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMjgxNDcsImV4cCI6MjA1OTYwNDE0N30.6Ke8zKFPBPJQXHZewvJ1leWqopJf5qbiYmxKxcFpsjg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: false
    }
  }
);
